CREATE TABLE users(
    `id` INTEGER UNIQUE NOT NULL,
    `name` VARCHAR(25) UNIQUE NOT NULL,
    `pos_x` FLOAT DEFAULT 1743.8944,
    `pos_y` FLOAT DEFAULT -1859.5548,
    `pos_z` FLOAT DEFAULT 14.5786,
    PRIMARY KEY(`id` AUTOINCREMENT)    
);